### ISSUE TITLE
Wemos ESP32 (The skitch won't install)

### ISSUE THREAD

**Issue by Dan4ic** [shubhamxbajaj/Smart-Water-Controller#1]
Doesn't fit skitch on the Wemos ESP32. 
Error:

`C:\Users\Artem\AppData\Local\Temp\.arduinoIDE-unsaved2023112-28960-4h1eu7.4uy7q\sketch_feb12b\sketch_feb12b.ino:9:89: fatal error: ESP8266WiFi.h: No such file or directory
compilation terminated.

exit status 1

Compilation error: ESP8266WiFi.h: No such file or directory`

**Comment by shubhamxbajaj** [comment]
You need to change the board to NodeMCU on Arduino IDE.

**Comment by Dan4ic** [comment]
> You need to change the board to NodeMCU on Arduino IDE.

similar error
https://skr.sh/sIM0UNJ6daS
https://skr.sh/sIMuVljfIkY

**Comment by shubhamxbajaj** [comment]
Please refer to this.

https://stackoverflow.com/questions/50080260/arduino-ide-cant-find-esp8266wifi-h-file

Let me know if you still face the issue

**Comment by Dan4ic** [comment]
> Please refer to this.
> 
> https://stackoverflow.com/questions/50080260/arduino-ide-cant-find-esp8266wifi-h-file
> 
> Let me know if you still face the issue

Thank you. But unfortunately could not solve the problem for the ESP32 use board
Apparently the ESP32 board is not supported by the current project, you need to change the code....

I saw a similar problem on another resource where they say that ESP32 may not support ESP8266 project
https://community.platformio.org/t/stuck-fatal-error-esp8266wifi-h-no-such-file-or-directory-when-compiling/28400/2

**Comment by shubhamxbajaj** [comment]
As mentioned in the README file, I was using NodeMCU(ESP8266) for this project. If you want to use ESP32 you will have to import the appropriate library and make changes to the code.

**Comment by Dan4ic** [comment]
> If you want to use ESP32 you will have to import the appropriate library and make changes to the code.

Unfortunately, I can't program.

**Comment by shubhamxbajaj** [comment]
NA
